image: debian:bullseye
before_script:
  - apt update -qy
  - apt install -y --no-install-recommends python3-wheel python3.8 python3.8-venv python3.8-distutils python3-pytest git make pipenv
  - pipenv --version

variables:
  LC_ALL: "C.UTF-8"
  LANG: "C.UTF-8"

test_python:
  script:
    - pipenv install --dev --deploy
    - pipenv run make test
